### PR TITLE
Create docker-compose-traefik.yml

### PR DESCRIPTION
**Pull request by vincenttisseront**
Alternative docker-compose to use traefik reverse proxy

### CODE REVIEW

**Comment by vincenttisseront** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ab-smith** [comment]
thank you @vincenttisseront for this interesting suggestion and welcome to the community 🤗
speed reading through this: aren't we missing the service and image of Traefik here?

**Comment by vincenttisseront** [comment]
My traefik service is in another docker-compose, it's a global traefik with multiple service behind it. The configuration is really simple just manage certificate with traefik
do you need the docker compose of traefik ?

**Comment by ab-smith** [comment]
Yes, I think it will be useful to make this deployment mode autonomous for the others, once you’ve cleaned it out of your specific setup of course

**Comment by vincenttisseront** [comment]
Traefik docker compose

version: "3.9"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./tls.yml:/etc/traefik/settings/dynamic.yml"
      - "./certs:/certs"
    networks:
      - front

networks:
  front:
    external: true

**Comment by ab-smith** [comment]
we'll merge this and add another flavor with traefik instead of caddy

**Review by ab-smith — APPROVED** [review]
need anothert service for traefik to make this flavor autonomous. Can be done in another PR

**Pull request merged**
