### PR TITLE
Fix Donut Chart

### PR DESCRIPTION
**Pull request by monsieurswag**

### CODE REVIEW

**Comment by monsieurswag** [comment]
recheck

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
There is an issue with the colours, they should follow the convention of the risk matrix.

**Comment by monsieurswag** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by monsieurswag** [comment]
recheck

**Review by eric-intuitem — APPROVED** [review]
LGTM

**Pull request merged**
