### PR TITLE
Set up django-silk profiler

### PR DESCRIPTION
**Pull request by nas-tabchiche**

### CODE REVIEW

**Comment by Mohamed-Hacene** [comment]
It works fine until I click on a specific request and get that error: 
Screenshot from 2024-03-04 16-35-26

**Comment by nas-tabchiche** [comment]
> It works fine until I click on a specific request and get that error: 
> 
> Screenshot from 2024-03-04 16-35-26
> 
> 

Which version of python are you running?

**Comment by nas-tabchiche** [comment]
This might be helpful to you: https://stackoverflow.com/a/52951224

**Comment by Mohamed-Hacene** [comment]
Fix is to install lib2to3 specifying the python version we use: `sudo apt install python3.11-lib2to3` for python3.11

**Review by Mohamed-Hacene — APPROVED** [review]
Ok

**Pull request merged**
