### PR TITLE
Show an error modal when trying to access the scoring assistant without an imported risk matrix

### PR DESCRIPTION
**Pull request by monsieurswag**
Things we can do in the future :

- Improve the appearance of the modal. (the 'displayJSONModal' modal type is not meant to dispay a single string).
- We could store a boolean value in the sessionStorage to track if the user has an imported risk matrix available or not in the future in order to make the load time of the scoring assistant faster (because there will be no need to fetch each time we click on the link of the scoring assistant)

### CODE REVIEW

**Review by eric-intuitem — APPROVED** [review]
OK for me with a gentler message.

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
OK, but functional test broken, to be fixed.

**Comment by Alexdev8** [comment]
> The functional test errors surely come from this behavior :
> 
> const clickEvent = new MouseEvent('click', { bubbles: true, cancelable: false }); event.target.dispatchEvent(clickEvent);
> 
> When the user clicks on the scoring-assistant link the click event is cancelled with event.preventDefault(), and if there is at least one imported risk matrix the code dispatch a non-cancelable click event on the scoring-assistant link which loads the page of the scoring assistant. The test seems to no detect the page loaded because this system makes the page loading a bit different from the other sidebar links.
> 
> So the problem is not from the code of this PR but rather from the tests that don't support this behavior for the moment.

@monsieurswag I just pushed a fix for the tests.
The problem was that the scoring assistant page behavior changed depending on either there is no risk matrix imported and therefore a modal is displayed or either there is one and the page is loaded like usual. The test now handle both cases.

**Review by eric-intuitem — APPROVED** [review]
GG.

**Pull request merged**
