### PR TITLE
Put the is_publised attribute in the AbstractBaseModel class

### PR DESCRIPTION
**Pull request by monsieurswag**

### CODE REVIEW

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
Please see the new DoD.

**Review by nas-tabchiche — CHANGES_REQUESTED** [review]
Just a few things before we can merge this:

- In object importers, just set `is_published` to `True` since imported library objects are always published anyway https://github.com/intuitem/ciso-assistant-community/blob/fc86564e9f56511f21411d129a118d32236c81b8/backend/library/utils.py#L281
- Add `is_published=True` to `FrameworkImporter`, `RequirementNodeImporter` and `RiskMatrixImporter` in import functions

**Review by eric-intuitem — APPROVED** [review]
Now LGTM. I have desquashed the migrations, and avoid useless overriding of field in library.

**Review by nas-tabchiche — APPROVED** [review]
LGTM

**Pull request merged**
