### PR TITLE
proposal to improve the translation into Italian

### PR DESCRIPTION
**Pull request by atomikiss**
Using CISO Assistant, I realized that the translation into Italian cannot be improved, as the current one is done in a literary manner without taking spoken Italian into account.

Being a native speaker and a CIso Assistant user, I propose to edit the translation into Italian.

Here the link to the [file](https://github.com/atomikiss/ciso-assistant-community/blob/main/frontend/messages/it.json)

Thank you.
Best regards

### CODE REVIEW

**Comment by atomikiss** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by atomikiss** [comment]
Hi guys,
there are issues?

Or this review needs more time to be approved?

**Comment by ab-smith** [comment]
Hey, this is the feedback I gave you on our chat: 
- there are multiple strings that you’ve removed, any reason?
- the json format is broken because of the extra space after the “,” that’s why I’ve suggested installing npm and npx to be able to pull the prettier utility and fix it

**Comment by atomikiss** [comment]
Hi Ab, tomorrow I rearrange the file and change it on the pr, ok?

**Comment by atomikiss** [comment]
@eric-intuitem i don't understand if now it is ok.

**Comment by ab-smith** [comment]
closing this since it's a duplicate with the other one

**Pull request closed without merging**
