### PR TITLE
Templatize audit reports

### PR DESCRIPTION
**Pull request by tovam**
Because of #518 I looked into how the audit reports were created and saw that it could be enhanced.
This PR makes the creation of audit reports use templates, that should ease future work on them.
I tested a couple test cases and couldn't find anything modified by the new version, I hope I didn't miss anything.

### CODE REVIEW

**Comment by Mohamed-Hacene** [comment]
Hi @tovam, thanks a lot for this work ! 

it's an excellent improvement that would make it possible to better manage this report. This PR can save us a lot of time. I'll test it and help you merge it properly if everything's Ok.

**Comment by ab-smith** [comment]
Hello @tovam great contribution indeed, thank you!
we’ve fixed the issue preventing the startup test to pass, please sync your branch with the recent main and we should be able to proceed

**Comment by tovam** [comment]
I'm glad it will help
I just updated the branch but it looks like there are missing checks

**Comment by Mohamed-Hacene** [comment]
Hey @tovam, 
I made the checks passed, don't worry
Would you mind if I added some translations for the audit report in your PR?

**Comment by ab-smith** [comment]
better to merge it first @Mohamed-Hacene  and create a PR on our side to continue that because it's a fork-based PR

**Comment by tovam** [comment]
Please merge as you like, tell me if you need anything from me

**Review by ab-smith — APPROVED** [review]

**Pull request merged**
