### PR TITLE
Feat/translate libraries

### PR DESCRIPTION
**Pull request by Mohamed-Hacene**

### CODE REVIEW

**Review by eric-intuitem — COMMENTED** [review]
Are the exclusions for "annotation" justified?

**Comment by eric-intuitem** [comment]
should fix #590

**Comment by Mohamed-Hacene** [comment]
> Are the exclusions for "annotation" justified?

No, it was a misunderstanding from my side

**Review by eric-intuitem — APPROVED** [review]
LGTM

**Pull request merged**
