### PR TITLE
Models/add result field to requirement assessment

### PR DESCRIPTION
**Pull request by nas-tabchiche**

### CODE REVIEW

**Comment by Mohamed-Hacene** [comment]
Before to merge it:
- [ ] Fix reports
- [ ] Add status chart

**Comment by Mohamed-Hacene** [comment]
Ready to be merged

**Review by Mohamed-Hacene — APPROVED** [review]
0k, @eric-intuitem @ab-smith can you try switching from `main` to this branch with one or more pre-filled audits to test the migration?

**Review by ab-smith — APPROVED** [review]

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
Problem when displaying a framework

**Review by eric-intuitem — APPROVED** [review]
LGTM now

**Pull request merged**
