### PR TITLE
Fix objects_meta always counting 1 object even when there is more than that

### PR DESCRIPTION
**Pull request by monsieurswag**
Before fix: overview_problem_libraries
After fix: overview_problem_libraries_fix

### CODE REVIEW

**Comment by ab-smith** [comment]
I don't see the fix on the branch, is it still ongoing?

**Comment by eric-intuitem** [comment]
This works well for a new installation. But it does not fix existing installations, where the wrong counters are already loaded in the library. A custom migration could fix that.

**Review by ab-smith — APPROVED** [review]
functional ok

**Review by nas-tabchiche — APPROVED** [review]
LGTM

**Pull request merged**
