### PR TITLE
Make The website work offline by using font-awesome locally

### PR DESCRIPTION
**Pull request by monsieurswag**

### CODE REVIEW

**Comment by monsieurswag** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by monsieurswag** [comment]
recheck

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
There is an interference with package-lock.json.
Shouldn't we use https://www.npmjs.com/package/svelte-fa instead?

**Review by eric-intuitem — CHANGES_REQUESTED** [review]
This breaks library import symbol in docker-compose

**Review by eric-intuitem — APPROVED** [review]
With last commit it works well

**Pull request merged**
