### PR TITLE
proposal to include two Italian framewroks in future releases of ciso assistant

### PR DESCRIPTION
**Pull request by atomikiss**
HI,
I opened this "now" because I have to use two Italian frameworks for my work.

One was released by AGID (National Agency for Digital Italy) and this is the link to the [official page](https://www.agid.gov.it/it/sicurezza/misure-minime-sicurezza-ict).

The other was released by CINI (National Interuniversity Consortium for Informatics) and this is the link to the [official page](https://www.cybersecurityframework.it/).

Since I believe in the CISO Assistant project and would like it to be used more in Italy, I would like it to have these two frameworks in future releases.

Thank you.

Best regards.

Below are links to the files in my GitHub repository:
[Framework Nazionale Cyber Security](https://github.com/atomikiss/ciso-assistant-community/blob/main/backend/library/libraries/fncsv2.yaml)
[Controlli Minimi AGID](https://github.com/atomikiss/ciso-assistant-community/blob/main/backend/library/libraries/Controlli-minimi-AGID.yaml)

### CODE REVIEW

**Comment by eric-intuitem** [comment]
Thanks for the work done! Here are a few initial remarks.
1/ The URL of the reference document must be provided in the description, and the description be more detailed.
2/ The depth=2 nodes should be merged with the depth1 nodes, and sub-nodes be raised accordingly.
3/ The provider shall be set to the entity that made the reference document.
4/ It would be simpler to make a review if the Excel is provided.

**Comment by atomikiss** [comment]
Hi eric and thank you for your advide.
I proceed as describe below:

1. I will edit the PR as per your indication
2. I don't know how to merge depth 2 into depth 1 and how to raise the subnode accordingly. Can you explain me how to?
3. I think to have done this, but I'm not sure
4. I attach the file here, but I would see the final file so I can learn how to do another framework.

Let me know.

Thankyou.

[Controlli-minimi-AGID.xlsx](https://github.com/user-attachments/files/17690687/Controlli-minimi-AGID.xlsx)
[fncsv2.xlsx](https://github.com/user-attachments/files/17690688/fncsv2.xlsx)

**Comment by eric-intuitem** [comment]
Please share the Excel files in the tools directory, and we will merge and improve your contribution.

**Comment by eric-intuitem** [comment]
[Controlli-minimi-AGID.xlsx](https://github.com/user-attachments/files/17693271/Controlli-minimi-AGID.xlsx)
[fncsv2.xlsx](https://github.com/user-attachments/files/17693272/fncsv2.xlsx)

**Comment by eric-intuitem** [comment]
@atomikiss please find the 2 corrected files. Please put them in /tools/it/, review them and regenerate the yaml.

**Comment by atomikiss** [comment]
@eric-intuitem in my repository, correct?

Let me know.

P.S. be patient but I am a newbie with github

**Pull request merged**
