### PR TITLE
Ca 545 add ref id to all editable objects

### PR DESCRIPTION
**Pull request by melinoix**
Added a reference ID to all editable projects : risk-assessments, domains, projects, compliance-assessments, applied-controls.

### CODE REVIEW

**Review by nas-tabchiche — DISMISSED** [review]
In almost all cases, a single PR should not have more than one single migration per app. This is mergeable once migrations are squashed and tests pass.

**Comment by melinoix** [comment]
-Have to modify tests/Api tests 
- projects tab have internal reference to replace & adjust the tests too
- domain is quite different so adapt the migration to it ( iam file instead of core file )

**Review by eric-intuitem — APPROVED** [review]
LGTM

**Review by eric-intuitem — APPROVED** [review]
LGTM

**Review by eric-intuitem — APPROVED** [review]

**Review by eric-intuitem — APPROVED** [review]

**Pull request merged**
