### PR TITLE
Fix/translation inconsistencies

### PR DESCRIPTION
**Pull request by monsieurswag**

### CODE REVIEW

**Comment by eric-intuitem** [comment]
custom.yaml should be in test directory.

**Review by Mohamed-Hacene — CHANGES_REQUESTED** [review]
Here is a list of inconsistencies still present:
- [ ] Risk levels in the risk assessment report
- [ ] Requirements description inside the flash mode
- [ ] Requirements description inside the audit report

**Review by Mohamed-Hacene — CHANGES_REQUESTED** [review]
There are still some point to translate:

- [ ] Requirements description in audit reports
- [ ] Probability and impact in scenarios detail/edit view

**Review by Mohamed-Hacene — APPROVED** [review]
0k

**Pull request merged**
