### PR TITLE
Correct plurial Questions or singular question

### PR DESCRIPTION
**Pull request by melinoix**
Corrected and showed the number of question to the user to fill in a Audit with questions inside. if only one, 1 Question if more nth Questions

### CODE REVIEW

**Review by nas-tabchiche — CHANGES_REQUESTED** [review]
Plural, not plurial

**Comment by eric-intuitem** [comment]
I did not realised it was also within the questionnaire.
1/ Remove "questions" line in the questionnaire, this is useless.
2/ Apply the correct plural form to the tag added in the compliance-assessments.

**Comment by eric-intuitem** [comment]
Works well. Let's provide all the translations to complete this task.

**Review by Mohamed-Hacene — CHANGES_REQUESTED** [review]
0k, can be merged after resolving conflicts

**Review by Mohamed-Hacene — APPROVED** [review]
0k

**Review by Mohamed-Hacene — APPROVED** [review]
0k

**Comment by Mohamed-Hacene** [comment]
@nas-tabchiche needs to review it to approve the requested changes

**Review by nas-tabchiche — APPROVED** [review]
LGTM

**Pull request merged**
